const ALPHABET_WORDS = {
  A: { word: "Apple", emoji: "\ud83c\udf4e" },
  B: { word: "Ball", emoji: "\ud83c\udfc0" },
  C: { word: "Cat", emoji: "\ud83d\udc31" },
  D: { word: "Dog", emoji: "\ud83d\udc36" },
  E: { word: "Egg", emoji: "\ud83e\udd5a" },
  F: { word: "Fish", emoji: "\ud83d\udc1f" },
  G: { word: "Goat", emoji: "\ud83d\udc10" },
  H: { word: "Horse", emoji: "\ud83d\udc34" },
  I: { word: "Ice cream", emoji: "\ud83c\udf66" },
  J: { word: "Jar", emoji: "\ud83c\udf6f" },
  K: { word: "Kite", emoji: "\ud83e\ude81" },
  L: { word: "Lion", emoji: "\ud83e\udd81" },
  M: { word: "Moon", emoji: "\ud83c\udf19" },
  N: { word: "Nest", emoji: "\ud83e\udea2" },
  O: { word: "Orange", emoji: "\ud83c\udf4a" },
  P: { word: "Pig", emoji: "\ud83d\udc37" },
  Q: { word: "Queen", emoji: "\ud83d\udc78" },
  R: { word: "Rain", emoji: "\ud83c\udf27\ufe0f" },
  S: { word: "Sun", emoji: "\u2600\ufe0f" },
  T: { word: "Tree", emoji: "\ud83c\udf33" },
  U: { word: "Umbrella", emoji: "\u2602\ufe0f" },
  V: { word: "Van", emoji: "\ud83d\ude90" },
  W: { word: "Water", emoji: "\ud83d\udca7" },
  X: { word: "Xylophone", emoji: "\ud83c\udfb5" },
  Y: { word: "Yak", emoji: "\ud83d\udc02" },
  Z: { word: "Zebra", emoji: "\ud83e\udd93" }
};

const WORDS = {
  2: [
    { word: "ox", emoji: "\ud83d\udc02" },
    { word: "go", emoji: "\ud83c\udfc3" },
    { word: "up", emoji: "\u2b06\ufe0f" },
    { word: "hi", emoji: "\ud83d\udc4b" },
    { word: "no", emoji: "\ud83d\udeab" },
    { word: "do", emoji: "\u2705" },
    { word: "we", emoji: "\ud83d\udc6b" },
    { word: "he", emoji: "\ud83d\udc66" },
    { word: "in", emoji: "\ud83d\udce5" },
    { word: "on", emoji: "\ud83d\udca1" },
    { word: "so", emoji: "\ud83d\udcaf" },
    { word: "my", emoji: "\ud83d\ude4b" },
    { word: "be", emoji: "\ud83d\udc1d" },
    { word: "it", emoji: "\ud83d\udc49" },
    { word: "at", emoji: "\ud83d\udccd" },
    { word: "an", emoji: "\ud83d\udd24" },
    { word: "to", emoji: "\u27a1\ufe0f" },
    { word: "if", emoji: "\ud83e\udd14" },
    { word: "by", emoji: "\ud83d\udc4d" },
    { word: "am", emoji: "\ud83d\ude0a" }
  ],
  3: [
    { word: "cat", emoji: "\ud83d\udc31" },
    { word: "dog", emoji: "\ud83d\udc36" },
    { word: "sun", emoji: "\u2600\ufe0f" },
    { word: "hat", emoji: "\ud83c\udfa9" },
    { word: "cup", emoji: "\u2615" },
    { word: "bus", emoji: "\ud83d\ude8c" },
    { word: "bed", emoji: "\ud83d\udecf\ufe0f" },
    { word: "pig", emoji: "\ud83d\udc37" },
    { word: "egg", emoji: "\ud83e\udd5a" },
    { word: "ant", emoji: "\ud83d\udc1c" },
    { word: "bat", emoji: "\ud83e\udd87" },
    { word: "cow", emoji: "\ud83d\udc04" },
    { word: "fox", emoji: "\ud83e\udd8a" },
    { word: "hen", emoji: "\ud83d\udc14" },
    { word: "jam", emoji: "\ud83c\udf53" },
    { word: "map", emoji: "\ud83d\uddfa\ufe0f" },
    { word: "net", emoji: "\ud83e\udd45" },
    { word: "pot", emoji: "\ud83c\udf72" },
    { word: "van", emoji: "\ud83d\ude90" },
    { word: "bug", emoji: "\ud83d\udc1b" },
    { word: "fan", emoji: "\ud83c\udf2c\ufe0f" },
    { word: "car", emoji: "\ud83d\ude97" },
    { word: "box", emoji: "\ud83d\udce6" },
    { word: "key", emoji: "\ud83d\udd11" },
    { word: "pen", emoji: "\ud83d\udd8a\ufe0f" }
  ],
  4: [
    { word: "duck", emoji: "\ud83e\udd86" },
    { word: "fish", emoji: "\ud83d\udc1f" },
    { word: "cake", emoji: "\ud83c\udf82" },
    { word: "bear", emoji: "\ud83d\udc3b" },
    { word: "lion", emoji: "\ud83e\udd81" },
    { word: "frog", emoji: "\ud83d\udc38" },
    { word: "star", emoji: "\u2b50" },
    { word: "moon", emoji: "\ud83c\udf19" },
    { word: "tree", emoji: "\ud83c\udf33" },
    { word: "rain", emoji: "\ud83c\udf27\ufe0f" },
    { word: "bird", emoji: "\ud83d\udc26" },
    { word: "book", emoji: "\ud83d\udcd6" },
    { word: "bell", emoji: "\ud83d\udd14" },
    { word: "ball", emoji: "\ud83c\udfc0" },
    { word: "ship", emoji: "\ud83d\udea2" },
    { word: "king", emoji: "\ud83e\udd34" },
    { word: "kite", emoji: "\ud83e\ude81" },
    { word: "lamp", emoji: "\ud83d\udca1" },
    { word: "deer", emoji: "\ud83e\udd8c" },
    { word: "goat", emoji: "\ud83d\udc10" },
    { word: "boat", emoji: "\u26f5" },
    { word: "drum", emoji: "\ud83e\udd41" },
    { word: "door", emoji: "\ud83d\udeaa" },
    { word: "leaf", emoji: "\ud83c\udf43" },
    { word: "nest", emoji: "\ud83e\udea2" }
  ],
  5: [
    { word: "apple", emoji: "\ud83c\udf4e" },
    { word: "horse", emoji: "\ud83d\udc34" },
    { word: "house", emoji: "\ud83c\udfe0" },
    { word: "tiger", emoji: "\ud83d\udc2f" },
    { word: "snake", emoji: "\ud83d\udc0d" },
    { word: "bread", emoji: "\ud83c\udf5e" },
    { word: "chair", emoji: "\ud83e\ude91" },
    { word: "cloud", emoji: "\u2601\ufe0f" },
    { word: "grape", emoji: "\ud83c\udf47" },
    { word: "lemon", emoji: "\ud83c\udf4b" },
    { word: "mouse", emoji: "\ud83d\udc2d" },
    { word: "ocean", emoji: "\ud83c\udf0a" },
    { word: "paint", emoji: "\ud83c\udfa8" },
    { word: "plant", emoji: "\ud83c\udf31" },
    { word: "queen", emoji: "\ud83d\udc78" },
    { word: "shark", emoji: "\ud83e\udd88" },
    { word: "smile", emoji: "\ud83d\ude04" },
    { word: "spoon", emoji: "\ud83e\udd44" },
    { word: "train", emoji: "\ud83d\ude82" },
    { word: "water", emoji: "\ud83d\udca7" },
    { word: "wheel", emoji: "\u2699\ufe0f" },
    { word: "eagle", emoji: "\ud83e\udd85" },
    { word: "candy", emoji: "\ud83c\udf6c" },
    { word: "dance", emoji: "\ud83d\udc83" },
    { word: "dress", emoji: "\ud83d\udc57" }
  ],
  6: [
    { word: "banana", emoji: "\ud83c\udf4c" },
    { word: "rabbit", emoji: "\ud83d\udc30" },
    { word: "turtle", emoji: "\ud83d\udc22" },
    { word: "monkey", emoji: "\ud83d\udc35" },
    { word: "flower", emoji: "\ud83c\udf3b" },
    { word: "orange", emoji: "\ud83c\udf4a" },
    { word: "castle", emoji: "\ud83c\udff0" },
    { word: "cookie", emoji: "\ud83c\udf6a" },
    { word: "dragon", emoji: "\ud83d\udc09" },
    { word: "forest", emoji: "\ud83c\udf32" },
    { word: "garden", emoji: "\ud83c\udf37" },
    { word: "kitten", emoji: "\ud83d\udc31" },
    { word: "pencil", emoji: "\u270f\ufe0f" },
    { word: "pillow", emoji: "\ud83d\udecb\ufe0f" },
    { word: "rocket", emoji: "\ud83d\ude80" },
    { word: "spider", emoji: "\ud83d\udd77\ufe0f" },
    { word: "window", emoji: "\ud83e\ude9f" },
    { word: "basket", emoji: "\ud83e\uddc2" },
    { word: "butter", emoji: "\ud83e\uddc8" },
    { word: "candle", emoji: "\ud83d\udd6f\ufe0f" },
    { word: "cherry", emoji: "\ud83c\udf52" },
    { word: "donkey", emoji: "\ud83d\udc34" },
    { word: "parrot", emoji: "\ud83e\udd9c" },
    { word: "peanut", emoji: "\ud83e\udd5c" },
    { word: "zipper", emoji: "\ud83e\uddf7" }
  ]
};
